### ISSUE TITLE
CheckboxWithLabel returns empty array instead of true

### ISSUE THREAD

**Issue by prionkor** [stackworx/formik-material-ui#114] opened 2019-11-09 14:32 UTC
Below is how I am implementing the checkbox.

                              <Field
                                    Label={{label: 'Remember me'}}
                                    checked={false}
                                    onChange={() => console.log('checked')}
                                    name="remember"
                                    value="1"
                                    color="primary"
                                    component={CheckboxWithLabel}
                                />

When I check the box it returns empty array instead of boolean. This causes the error below:

```
Warning: Failed prop type: Invalid prop `checked` of type `array` supplied to `ForwardRef(Checkbox)`, expected `boolean`.
```

**Comment by mediba-carlos** [comment] 2019-11-13 01:16
I'm having the same issue, but with a `Switch` element. Had to downgrade Formik to version 2.0 to make it work, but maybe 1.5.8 is safer...
Would be great if somebody could tell us when this might get solved or if there is any other work around.

**Comment by binarymind** [comment] 2019-11-13 16:12
the problem appears since version 1.0.0
can check here : https://codesandbox.io/s/competent-kare-j2y7g

**Comment by binarymind** [comment] 2019-11-13 16:20
the problem appeared with formik 2.0.1-rc5 to be precise : https://codesandbox.io/s/competent-kare-j2y7g

**Comment by riderodd** [comment] 2019-11-15 14:15
Same problem for me, downgrading formik to 2.0.0 temporarily fix the issue, but throws other warnings.
Checking PR #113 to see if it fixes

**Comment by riderodd** [comment] 2019-11-15 15:47
I've managed to get i work but couldn't use formik-material-ui, here's a hack while waiting for a fix:

```jsx
import { Formik, Form, Field, ErrorMessage } from 'formik';
import Switch from '@material-ui/core/Switch';
import FormControlLabel from '@material-ui/core/FormControlLabel';

<Formik initialValues={{ switch: false }}>{form => (
    <Form className="form">
        <FormControlLabel
          control={<Field name="switch" component={Switch} />}
          label="My label"
          name="switch"
          required={true}
          onChange={(ev, checked) => { form.setFieldValue('terms', checked); }}
        />
        <ErrorMessage name="terms" />
    </Form>
)}</Formik>
```

Using onChange prop I can manually set the form state using the Formik context.

**Comment by prionkor** [comment] 2019-11-15 19:49
@riderodd Thanks for the solution. Below I have added the `CheckBox` version of your solution.

```
<FormControlLabel
     control={<Field name="remember" component={Checkbox} />}
     label="Remember me"
     name="remember"
     onChange={(ev, checked) => { setFieldValue('remember', checked); }}
     />
```

**Comment by codingfunwoody** [comment] 2019-11-20 04:38
https://github.com/jaredpalmer/formik/blob/c0fe1b928b903405b8591f7250b66a8aa9828650/src/Formik.tsx#L1052

```
export const fieldToCheckbox = ({
  field,
  form: { isSubmitting },
  disabled,
  ...props
}: CheckboxProps): MuiCheckboxProps => {
  return {
    disabled: disabled != undefined ? disabled : isSubmitting,
    ...props,
    ...field,
    // TODO handle indeterminate
    checked: field.value,
    value: field.value ? 'true' : 'false',
  };
};
```

**Comment by cardimajs** [comment] 2019-11-21 23:31
same problem using Switch

**Comment by r3mi** [comment] 2019-11-24 21:07
For `Switch` (boolean behaviour i.e. not multiple), I managed to make it work in Formik 2 natively (without  formik-material-ui), using `<Field as>` syntax.
Extract:
```tsx
import Switch from "@material-ui/core/Switch"
import FormControlLabel from "@material-ui/core/FormControlLabel"
import { Field, Form, Formik } from "formik"
...<Formik><Form>...
              <FormControlLabel
                control={
                  <Field
                    name="someBool"
                    id="someBool"
                    type="checkbox" // seems required to handle correctly initial values of true
                    as={Switch}
                  />
                }
                label="Subunit based placement"
              />
```
using formik 2.0.6 and material-ui 4.6.1

**Comment by Amritpd** [comment] 2020-01-18 05:07
This bug is still happening. Any long term solution?

Thanks!

**Comment by cliedeman** [comment] 2020-01-20 18:59
You could be running into [expected behaviour](https://jaredpalmer.com/formik/docs/migrating-v2#checkboxes-and-select-multiple). Can you provide a code sandbox that displays the issue?

Also please try with the new 2.0.0-alpha.2 release

**Comment by SQReder** [comment] 2020-01-21 11:24
The issue still actual for 2.0.0-alpha.2
https://codesandbox.io/s/condescending-fog-8153u

**Comment by SQReder** [comment] 2020-01-21 11:55
I've investigated a little and seems to be this issue related to Formik itself. When you use non-boolean value as the default for checkbox field it fails into an array

Demo: https://codesandbox.io/s/pedantic-tdd-el2df

Core issue somewhere there:
https://github.com/jaredpalmer/formik/blob/master/packages/formik/src/Formik.tsx#L1155

If you use boolean initial value for checkbox it acts correctly 😎

**Comment by cliedeman** [comment] 2020-01-21 13:01
@SQReder Thanks for the investigation. 
The error/warning also seems to be gone so we can probably close this issue now

**Comment by mrjdavidfg** [comment] 2020-02-12 21:45
For Checkboxes with many options, I did this and it works for me. Without using `formik-material-ui`.
```
<FormControl component="fieldset">
  <FormLabel component="legend">Choose the ones you want</FormLabel>
  <FormGroup>
    {options.map(opt => (
      <FormControlLabel
        control={
          <Field
            name="my_options"
            id="my_options"
            value={opt.value}
            as={Checkbox}
          />
        }
        key={opt.value}
        label={opt.label}
      />
    ))}
  </FormGroup>
  <FormHelperText>Be careful</FormHelperText>
</FormControl>
```

`"formik": "^2.1.4"`

**Comment by cliedeman** [comment] 2020-02-12 21:49
Please retry with the latest version.
Also check the [migration notes](https://stackworx.github.io/formik-material-ui/docs/guide/migrating)

**Comment by mrjdavidfg** [comment] 2020-02-13 03:51
Done! With the latest version (formik-material-ui v2.0.0-beta.1) is now like this:

```
<FormControl component="fieldset">
  <FormLabel component="legend">
    Choose the ones you want
  </FormLabel>
  <FormGroup>
    {options.map(opt => (
      <Field
        component={CheckboxWithLabel}
        type="checkbox" //REQUIRED to work with non-boolean options
        name="my_options"
        value={opt.value}
        key={opt.value}
        Label={{ label: opt.label }}
      />
    ))}
  </FormGroup>
  <FormHelperText>Be careful</FormHelperText>
</FormControl>
```

Looks good. But the documentation does not say anything about the `type="checkbox"` to work with non-boolean values.

**Comment by cliedeman** [comment] 2020-02-13 07:44
@mrjdavidfg glad you got it working

> But the documentation does not say anything about the type="checkbox" to work with non-boolean values.

What exactly do you mean?

**Comment by mrjdavidfg** [comment] 2020-02-13 12:02
As @r3mi also said, its necessary the `type="checkbox"` prop on the Field for it to work, if not added, the changes in the checkbox status will not be reflected in the Formik form values.

Example: https://codesandbox.io/s/material-demo-7zxgy

**Comment by cliedeman** [comment] 2020-02-13 12:07
Ok I am going to close this out then

**Closed by cliedeman** 2020-02-13 12:07 UTC
Labels: waiting-on-reply

**Comment by maurosbu** [comment] 2020-10-28 11:08
@mrjdavidfg thx. I tried to modify your example using integer values instead o string ones and then I get the following strange behaviour: if you click on a checkbox then the value is added, but the checkbox remain unchecked. 

Any idea on this? Casting integers to string is a workaround.

**Comment by cliedeman** [comment] 2020-10-28 11:52
Hi @maurosbu 

If I remove component (taking formik-material-ui) out of the picture I still get the same issue.

```tsx
<Field
                    type="checkbox"
                    name="numbers"
                    key={opt.label}
                    value={opt.value}
                    Label={{ label: opt.label }}
                  />
```

so this is likely an issue or expected behaviour of formik itself

**Comment by maurosbu** [comment] 2020-10-28 12:42
@cliedeman thx, I will check / open an issue on Formik repo.
