### ISSUE TITLE
Pickers make Formik consider the Form to be always invalid

### ISSUE THREAD

**Issue by apollux** [stackworx/formik-material-ui#140] opened 2020-02-10 15:14 UTC
Including the TimePicker, DatePicker or DateTimePicker in a form makes Formik consider the form as invalid. The errors property for the picker is set to an empty string and apparently that makes the form invalid.

Consider the following example:
```javascript
import * as React from "react";
import { Formik, Form } from "formik";
import { TextField } from 'formik-material-ui'
import {
  TimePicker,
  DatePicker,
  DateTimePicker
} from "formik-material-ui-pickers";
import { MuiPickersUtilsProvider } from "@material-ui/pickers";
import DateFnsUtils from "@date-io/date-fns";

export default function App() {
  return (
    <MuiPickersUtilsProvider utils={DateFnsUtils}>
      <Formik
        initialValues={{
          email: "",
          dateTime: new Date()
        }}
      >
        {({ errors, isValid }) => (
          <Form>
            <TextField name="field" label="Field" />
            <br />
            <TimePicker name="time" label="Time" />
            <br />
            <DatePicker name="date" label="Date" />
            <br />
            <DateTimePicker name="dateTime" label="Date Time" />
            <br />
            errors:
            <pre>{JSON.stringify(errors, null, 2)}</pre>
            isValid: {isValid ? "true" : "false"}
          </Form>
        )}
      </Formik>
    </MuiPickersUtilsProvider>
  );
}

```
this will show errors to be:
```
{
  "time": "",
  "date": "",
  "dateTime": ""
}
```
and the `isValid` field to be `false`.
https://codesandbox.io/s/sad-moore-i4b4k

**Comment by Chmielik** [comment] 2020-02-11 11:05
Same issue there

**Comment by Chmielik** [comment] 2020-02-11 15:11
@apollux it looks like this version of @material-ui/pickers@3.2.5 (https://github.com/mui-org/material-ui-pickers/releases/tag/v3.2.5) is breaking the validation. Using 3.2.4 solves the problem.

**Comment by cliedeman** [comment] 2020-02-12 21:42
There have been a number of [releases](https://github.com/mui-org/material-ui-pickers/releases). Is this still happening?

**Comment by andre-aktivconsultancy** [comment] 2020-02-13 07:46
Yes I tested this with:
`@material-ui/pickers:3.2.10`
`@formik-material-ui-picker:0.0.4`
`@formik-material-ui:2.0.0-alpha.3`
`@formik:2.1.4`

I forked your codesandbox with the 0.0.6 release of formik-material-ui-picker and reproduced it there as well: https://codesandbox.io/s/stupefied-germain-elclg

**Comment by cliedeman** [comment] 2020-02-13 11:22
Fixed in 0.0.8 - https://codesandbox.io/s/stupefied-germain-elclg

**Comment by andre-aktivconsultancy** [comment] 2020-02-13 11:36
Awesome! Thank you :)

**Closed** 2020-02-13 11:45 UTC
Labels: question, waiting-on-reply

**Comment by CharlestonREM** [comment] 2021-02-24 20:28
### time and date pickers default to current timestamp even if initialValues are set to empty strings
The initial values are set to empty strings, but somehow the fields supply the current time. The pickers are based on the codesandbox date picker and time picker.


![image](https://user-images.githubusercontent.com/74624127/109061373-96230380-76b4-11eb-8dcb-703a66353aa7.png)

**Comment by CharlestonREM** [comment] 2021-02-24 20:34
> ### time and date pickers default to current timestamp even if initialValues are set to empty strings
> The initial values are set to empty strings, but somehow the fields supply the current time. The pickers are based on the codesandbox date picker and time picker.

This was not the problem. I needed to set the value of the date picker and time picker fields to  `null` in the initial values.

https://github.com/stackworx/formik-material-ui/issues/147#issuecomment-785355948
