### ISSUE TITLE
OnChange is not triggered in Select component?

### ISSUE THREAD

**Issue by zonecheung** [stackworx/formik-material-ui#53] opened 2019-01-01 01:42 UTC
Hello There,

I tried to use the `Select` component from "formik-material-ui" wrapped inside my custom component, however, the `onChange` event wasn't triggered when I added to the component.

The code is as simple as follows:
```
    const handleChange = (x, y) => {
      console.log(x, y);  // Never called.
    };

    return (<Select {...props} onChange={handleChange} />);
```

I'm pretty new to react, formik, and material-ui. Any idea what I've done wrong? Is there any other attribute I need to set?

Thanks in Advance,
~ John

**Comment by FDT2k** [comment] 2019-05-27 09:54
Had the same problem, I had to handle onChange in the <Form> component.

**Comment by cliedeman** [comment] 2019-05-30 15:57
Duplicate of #50

**Closed by cliedeman** 2019-05-30 15:57 UTC
